# Generated by Django 4.2.11 on 2024-06-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img_id", models.CharField(max_length=25)),
                ("event_id", models.CharField(max_length=25)),
                ("publisher_id", models.CharField(max_length=25)),
                ("published_date", models.DateTimeField(auto_now_add=True)),
                ("file", models.FileField(upload_to="uploads/")),
            ],
        ),
    ]
