# Generated by Django 4.2.11 on 2024-06-01 17:39

import apiservice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiservice", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="file",
            field=models.FileField(upload_to=apiservice.models.image_dir_path),
        ),
    ]
