# Generated by Django 4.2.11 on 2024-06-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiservice", "0002_alter_image_file"),
    ]

    operations = [
        migrations.RemoveField(model_name="image", name="id",),
        migrations.AlterField(
            model_name="image",
            name="img_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
